### ISSUE TITLE
Beta Functionality Roadmap

### ISSUE THREAD

**Issue by bnbalsamo** [uchicago-library/separationsheet_site#1]
In order to bring this project up to beta functionality the following will have to be done:

- [x] Decision made on storage solution
- [x] Storage solution library code is written, implementing the same methods and signatures as [FakeDB](https://github.com/uchicago-library/separationsheet_site/blob/master/separationsheet_site/blueprint/__init__.py#L81) if the same logic is to be used.
- [x] Storage back end is hard coded, in the instance there is one and only one storage solution decided upon, or made configurable via environmental variable(s) if developed as a configurable option.
    - [ ] Logic for instantiating the storage solution is moved out of the module level, and into a callback run on application instantiation, if storage solution is configurable.
- [x] Application is hosted accessible to relevant SPCL and DLDC actors, and shibbolized in order to limit access appropriately.

**Comment by verbalhanglider** [comment]
Storage is hard-coded. This project does not warrant making storage configurable at this time.
